version: '3'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/srv

  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./src:/srv
