name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  svelte:

    runs-on: ubuntu-latest
    needs: php

    steps:
    - uses: actions/checkout@v2

    - name: Cache NPM packages
      id: npm-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-js-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-js-

    - name: Install dependencies
      run: npm ci

    - name: Run code check
      run: npm run check

    - name: Make a working website out of all
      run: |
        npm run build --if-present
        mv Frontend/* .
        rmdir Frontend
        rsync -avhrz --delete --filter=". rsync_filter.txt" . /srv/TODO
